### ISSUE TITLE
Wireframe: Page "Event Calendar"

### ISSUE THREAD

**Issue by VMLVaske** [GeneralMagicio/TE-Academy#31]
The wireframe for the page "Event Calendar" has an implementation for a search field. 

See this screenshot of current fields (search bars + drop down fields to filter for certain attributes). 
![Screenshot 2022-06-27 at 13.03.42.png](https://images.zenhubusercontent.com/62a9dd2e14bf035c3dc510d9/6903ba07-6937-4af3-92ad-cf0b32fed27f)

The discussion of which fields to include is still open. 
The "implementability" of the fields is an issue that needs dev input: what's the easiest thing to implement - where do the boarders lie from what the LMS API can offer here? 

Angela would like to have the following options to search / filter for: 
* weekday (i.e. shows all events on thursdays)
* location (difference between digital & meatspace events, needs to also show the location of the meatspace events & be searchable, i.e. for meatspace events close to my own location) 
* searchable by month (i.e. show all events for say march 2022, june 2022 - opens the question on how many months in advance are searchable and will the "months in advance" selectors be updated by themselves or manually? => would it be easier to just implement a calendar option where a date or a timeframe can be selected?)

**Comment by marthendalnunes** [comment]
@VMLVaske the events data will come from the CMS rather than the LMS, therefore there's no limitation to what can be displayed given the data is structured accordingly in the CMS. All the search/filter options are feasible to implement, and regarding the searchable by month, we can have either a calendar to pick specific dates or a fixed option to x months in advance, it's up to the design/UX team.
