### ISSUE TITLE
web3 link functionality on website

### ISSUE THREAD

**Issue by Vyvy-vi** [GeneralMagicio/TE-Academy#5]
We'd also need an option on the website where people can associate their web3 wallets with their signed up account on the website.

This functionality could be linked to the sign up/log in functionality implemented in #4, but according to Angela, it would be appreciated if a web3 login doesn't act as a "barrier of entry", as many aspiring TEs can have no experience with wallets. 
Moreover, we'd also strictly need every user to provide an email or generates a user-id, so that we can create an account for them inside LearnWorlds using their SSO end-point - https://learnworlds.dev/docs/api/58052c1c3066e-single-sign-on

*We should discuss more about this.

**Comment by VMLVaske** [comment]
Closing this discussion, as we agreed to not make the platform a dApp (where users actually connect their wallets), but a normal web2 platform that has the option for the user to input their web3 address, so that a minted NFT can be send there. 

Specifics: 
Users can input their web3 address. Users cannot change their address (for the first MVP that's due by the end of August anyway). Users cannot have multiple addresses.
